stages:
  - page_build
  - page_deploy

site:
  stage: page_build
  image: nixos/nix
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  cache:
    - key:
        files:
          - flake.nix
          - flake.lock
      paths:
        - /nix/store
  script:
    - nix --experimental-features 'nix-command flakes' build .?submodules=1#site
  artifacts:
    paths:
      - result/public

pages:
  image: alpine
  stage: page_deploy
  environment: production
  script:
    - mv result/public public
  artifacts:
    paths:
      - public
  only:
    - master
  needs:
    - site
