[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"



[tool.hatch.envs.test]
dependencies = [
    "coverage",
    "cython",
    "jax[cpu]",
    "scipy",
    "matplotlib",
    "pyvirtualdisplay",
]

[tool.hatch.envs.test.scripts]
run = "python -m unittest discover"
run-cov = "coverage run -m unittest discover"
cov-combine = "coverage combine"
cov-report = "coverage report"

[[tool.hatch.envs.test.matrix]]
python = ["3.8", "3.9", "3.10", "3.11", "3.12"]
gym = ["gym", "gymnasium"]

[tool.hatch.envs.test.overrides]
matrix.python.dependencies = [
    { value = "ray", if = ["3.8", "3.9", "3.10", "3.11"] },
]
matrix.gym.dependencies = [
    { value = "gym", if = ["gym"] },
    { value = "gymnasium", if = ["gymnasium"] },
]

[tool.hatch.envs.docs]
dependencies = [
    "sphinx",
    "sphinx-automodapi",
    "sphinx_rtd_theme",
]


[tool.coverage.run]
branch = true
plugins = "Cython.Coverage"
parallel = true
relative_files = true


[tool.coverage.paths]
source = [ "cpprb/" ]


[tool.coverage.report]
show_missing = true
