baseURL = "https://ymd_h.gitlab.io/cpprb/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "cpprb"
theme = "hugo-theme-relearn"
themesdir = "themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= false
publishDir = "../public"

[params]
  description = "cpprb: Fast Flexible Replay Buffer Library for Reinforcement Learning"
  author = "Hiroyuki Yamada"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = true
  themeVariant = "cpprb"
  disableInlineCopyToClipBoard = true
  images = ["/cpprb/images/OGP.png"]
  custom_css = ["css/custom.css"]

[outputs]
home = ['html', 'rss', 'print']

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-gitlab'></i> GitLab"
identifier = "ds"
url = "https://gitlab.com/ymd_h/cpprb"
weight = 10

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub Mirror"
identifier = "gh"
url = "https://github.com/ymd-h/cpprb"
weight = 15

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Class Reference"
identifier = "api"
url = "https://ymd_h.gitlab.io/cpprb/api/"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-comments'></i> User Forum"
identifier = "forum"
url = "https://github.com/ymd-h/cpprb/discussions"
weight = 25


[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-blog'></i> Author's Blog"
identifier = "blg"
url = "https://ymd_h.gitlab.io/ymd_blog/"
weight = 40
