name: CI

on:
  push:
  pull_request:


jobs:
  readme:
    container: iquiw/alpine-emacs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: emacs --batch README.org --eval '(org-md-export-to-markdown)'
      - uses: actions/upload-artifact@v4
        with:
          name: README
          path: README.md
  build_wheel:
    needs: readme
    strategy:
      matrix:
        runs-on: [macos-13, macos-14, windows-latest, ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: README
          path: README
      - run: mv README/README.md README.md
      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: |
            **/pyproject.toml
            **/setup.py
      - run: uvx -p 3.12 cibuildwheel
      - uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.runs-on }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
  build_targz:
    needs: readme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: README
          path: README
      - run: mv README/README.md README.md
      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: |
            **/pyproject.toml
            **/setup.py
      - run: uv run --no-project --with build python -m build --sdist
      - uses: actions/upload-artifact@v4
        with:
          name: dist-sdist
          path: dist/*.tar.gz
  upload:
    needs: [build_wheel, build_targz]
    environment: pypi
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    if: github.event_name == 'push' && startsWith(github.event.ref,'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: 'dist-*'
          path: dist
          merge-multiple: true
      - uses: pypa/gh-action-pypi-publish@release/v1
